# Each step starts in the checked-out source directory,
# environment variables aren't persisted across steps.

steps:
- checkout: self
  submodules: true
  fetchDepth: 50
- script: |
    set -ex
    cd ..
    if [ "$CI_OS" = "linux" ]; then
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get -q update
      sudo apt-get -yq install \
        curl git-core g++ ninja-build binutils-dev
    else
      # Download & extract Ninja
      curl -L -o ninja-mac.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip
      mkdir ninja
      tar -xf ninja-mac.zip -C ninja
    fi
  displayName: Install prerequisites
- script: |
    set -ex
    cd ..
    export PATH="$PWD/ninja:$PATH"
    cmake --version
    ninja --version
    mkdir build
    cd build
    cmake -G Ninja $BUILD_SOURCESDIRECTORY \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$PWD/../install \
      -DLLVM_TARGETS_TO_BUILD="$LLVM_TARGETS_TO_BUILD" \
      -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="$LLVM_EXPERIMENTAL_TARGETS_TO_BUILD" \
      -DLLVM_ENABLE_ASSERTIONS=$LLVM_ENABLE_ASSERTIONS \
      -DCOMPILER_RT_INCLUDE_TESTS=OFF \
      $BASE_CMAKE_FLAGS $EXTRA_CMAKE_FLAGS
    ninja install
  displayName: Build & install LLVM incl. LLD, compiler-rt and the Khronos SPIRV-LLVM-Translator
- script: |
    set -e
    cd ..
    if [ "${BUILD_SOURCEBRANCH:0:10}" = "refs/tags/" ]; then
      ARTIFACT_ID=${BUILD_SOURCEBRANCH:15}
    else
      ARTIFACT_ID=${BUILD_SOURCEVERSION:0:8}
    fi
    ASSERTS_SUFFIX=""
    if [ "$LLVM_ENABLE_ASSERTIONS" = "ON" ]; then
      ASSERTS_SUFFIX="-withAsserts"
    fi
    # Persist the ARTIFACT_ID and ASSERTS_SUFFIX variables for future steps
    echo "##vso[task.setvariable variable=ARTIFACT_ID]$ARTIFACT_ID"
    echo "##vso[task.setvariable variable=ASSERTS_SUFFIX]$ASSERTS_SUFFIX"
    artifactName=llvm-$ARTIFACT_ID-$CI_OS-x86_64$ASSERTS_SUFFIX
    mv install $artifactName
    mkdir artifacts
    XZ_OPT=-9 tar -cJf artifacts/$artifactName.tar.xz $artifactName
  displayName: Pack installation dir
- script: |
    set -e
    cd ..
    if [[ "$CI_OS" = "linux" && "$LLVM_ENABLE_ASSERTIONS" = "OFF" ]]; then
      artifactName=llvm-$ARTIFACT_ID.src
      XZ_OPT=-9 tar -cJf artifacts/$artifactName.tar.xz --exclude-vcs --transform=s,${BUILD_SOURCESDIRECTORY:1},$artifactName, $BUILD_SOURCESDIRECTORY
    else
      echo 'Skipping'
    fi
  displayName: Pack source dir
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: $(CI_OS)-x86_64$(ASSERTS_SUFFIX)
    targetPath: ../artifacts
  displayName: Publish artifact(s)
